
service: serverless-example

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  main:
    handler: dist/main.handler
    timeout: 10
    events:
      - http:
          method: ANY
          path: '/{proxy+}'
